CC = gcc
CFLAGS = -Wall -Wextra -Iinclude
SRC = src/main.c src/grafo.c
OBJ = $(SRC:.c=.o)
TARGET = grafo_bfs

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)

clean:
	rm -f src/*.o $(TARGET)